# Generated by Django 3.2.7 on 2021-09-13 11:16

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default=blog.models.create_id, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
